[tool.poetry]
name = "core"
version = "0.1.0"
description = ""
authors = ["Wilson Anciro <konekred@gmail.com>"]
# packages = [{ include = "auth" }]

[tool.poetry.dependencies]
python = "3.9.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
